#ifndef EXTRANONCE_H_
#define EXTRANONCE_H_

#define EXTRANONCE2_MIN_BYTES 2U
#define EXTRANONCE2_MAX_BYTES 16U
#define EXTRANONCE2_HEX_MAX_LEN (EXTRANONCE2_MAX_BYTES * 2U)

#endif /* EXTRANONCE_H_ */
